skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
betting_engine = "FBXnZZHR3ndsE2oYak4EQaFTPZsEC7d34C8tQfE7hkm4"
oracle_adapter = "BfWcrr3Mv4StpqSyaMUZtsLLUTM9cLkNeaARRdwSFSCN"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
