skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
betting_engine = "67mbZdR3KxZxRxgKDMT7JbxtYU92C1y81Q4KKGQRkMMY"
liquidity_pool = "3wdXrPtrpX44sAhfZbK9MJVTwQ2ufai8pQ1C8TVHPexV"
oracle_adapter = "HwDVX9fTTxmnLBJwtig7ugsWuiqLh14pj71WtxQaaSSa"

[programs.testnet]
betting_engine = "H3ekojbWVFfzYnTmiNUejMkiB2pEQuf6wyH7QyyMQkz1"
liquidity_pool = "3jeWz6WQaM8DG5jRqoVff4FtsMVRjg9peGGMjjgUYRMY"
oracle_adapter = "Df1gfgegKEBJvKtyHdxUiwaohUkDQj9Pigdpgszk7XUL"

[provider]
cluster = "testnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
