skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
oracle_adapter = "6BVWCCQDjQDcjQYhmbzJ9DFWY9LyDojM3mYoWivrASaG"
betting_engine = "GoccKzkMS5BWRmrbLdGKzqKUUcksZB3DftW82F7boCoQ"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
